
const startScreen=document.getElementById('startScreen');
const menuScreen=document.getElementById('menuScreen');
const enterForestBtn=document.getElementById('enterForestBtn');
if(enterForestBtn){enterForestBtn.addEventListener('click',()=>{startScreen.classList.remove('active');menuScreen.classList.add('active');});}
const GATTUNGEN=[{"name": "Champignons/Egerlinge", "file": "cards/02_Champignons_Egerlinge.png"}, {"name": "Dachpilze", "file": "cards/06_Dachpilze.png"}, {"name": "Filzröhrlinge", "file": "cards/33_Filzroehrlinge.png"}, {"name": "Fälblinge", "file": "cards/16_Faelblinge.png"}, {"name": "Hallimasche", "file": "cards/37_Hallimasche.png"}, {"name": "Helmlinge", "file": "cards/22_Helmlinge.png"}, {"name": "Holzkremplinge", "file": "cards/28_Holzkremplinge.png"}, {"name": "Häublinge", "file": "cards/40_Haeublinge.png"}, {"name": "Kleine Schirmlinge", "file": "cards/03_Kleine_Schirmlinge.png"}, {"name": "Kraterellen/Trompeten", "file": "cards/35_Kraterellen_Trompeten.png"}, {"name": "Kremplinge", "file": "cards/27_Kremplinge.png"}, {"name": "Lacktrichterlinge", "file": "cards/13_Lacktrichterlinge.png"}, {"name": "Maronenröhrlinge", "file": "cards/30_Maronenroehrlinge.png"}, {"name": "Milchlinge", "file": "cards/18_Milchlinge.png"}, {"name": "Milchlinge (Lactifluus)", "file": "cards/19_Milchlinge_Lactifluus.png"}, {"name": "Pfifferlinge", "file": "cards/34_Pfifferlinge.png"}, {"name": "Raufußröhrlinge", "file": "cards/32_Raufussroehrlinge.png"}, {"name": "Riesenschirmlinge", "file": "cards/04_Riesenschirmlinge.png"}, {"name": "Risspilze", "file": "cards/14_Risspilze.png"}, {"name": "Ritterlinge", "file": "cards/09_Ritterlinge.png"}, {"name": "Rötelritterlinge (trad.)", "file": "cards/10_Roetelritterlinge_trad.png"}, {"name": "Röteltrichterlinge", "file": "cards/12_Roeteltrichterlinge.png"}, {"name": "Rötlinge", "file": "cards/08_Roetlinge.png"}, {"name": "Rüblinge", "file": "cards/24_Rueblinge.png"}, {"name": "Safranschirmlinge", "file": "cards/05_Safranschirmlinge.png"}, {"name": "Saftlinge", "file": "cards/21_Saftlinge.png"}, {"name": "Schleierlinge", "file": "cards/15_Schleierlinge.png"}, {"name": "Schmierröhrlinge", "file": "cards/31_Schmierroehrlinge.png"}, {"name": "Schnecklinge", "file": "cards/20_Schnecklinge.png"}, {"name": "Schwefelköpfe", "file": "cards/38_Schwefelkoepfe.png"}, {"name": "Schwindlinge", "file": "cards/23_Schwindlinge.png"}, {"name": "Schüpplinge", "file": "cards/41_Schuepplinge.png"}, {"name": "Seitlinge", "file": "cards/25_Seitlinge.png"}, {"name": "Steinpilze (enger Sinn)", "file": "cards/29_Steinpilze_enger_Sinn.png"}, {"name": "Stockschwämmchen", "file": "cards/39_Stockschwaemmchen.png"}, {"name": "Stoppelpilze", "file": "cards/36_Stoppelpilze.png"}, {"name": "Stummelfüßchen", "file": "cards/26_Stummelfuesschen.png"}, {"name": "Trichterlinge (enger/trad. Sinn)", "file": "cards/11_Trichterlinge_enger_trad_Sinn.png"}, {"name": "Täublinge", "file": "cards/17_Taeublinge.png"}, {"name": "Volvadachpilze", "file": "cards/07_Volvadachpilze.png"}, {"name": "Wulstlinge", "file": "cards/01_Wulstlinge.png"}];

const $=s=>document.querySelector(s);
const menu=$('#menuScreen'),trail=$('#trailScreen'),card=$('#cardScreen'),grid=$('#tileGrid'),img=$('#cardImage'),counter=$('#cardCounter');
let current=0,startX=0,startY=0;
function show(screen){[menu,trail,card].forEach(s=>s.classList.remove('active'));screen.classList.add('active');window.scrollTo(0,0)}
function buildTiles(){grid.innerHTML='';GATTUNGEN.forEach((g,i)=>{const b=document.createElement('button');b.className='genus-tile';b.innerHTML=`<span class="thumb" style="background-image:url('${g.file}')"></span><span>${g.name}</span>`;b.onclick=()=>openCard(i);grid.appendChild(b)})}
function openCard(i){current=(i+GATTUNGEN.length)%GATTUNGEN.length;img.src=GATTUNGEN[current].file;img.alt=GATTUNGEN[current].name;counter.textContent=`${current+1} / ${GATTUNGEN.length}`;show(card)}
function step(d){openCard(current+d)}
$('#trailBtn').onclick=()=>show(trail);$('#trailBack').onclick=()=>show(menu);$('#cardClose').onclick=()=>show(trail);$('#prevCard').onclick=()=>step(-1);$('#nextCard').onclick=()=>step(1);
card.addEventListener('touchstart',e=>{const t=e.changedTouches[0];startX=t.clientX;startY=t.clientY},{passive:true});
card.addEventListener('touchend',e=>{const t=e.changedTouches[0],dx=t.clientX-startX,dy=t.clientY-startY;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.25)step(dx<0?1:-1)},{passive:true});
document.addEventListener('keydown',e=>{if(!card.classList.contains('active'))return;if(e.key==='ArrowLeft')step(-1);if(e.key==='ArrowRight')step(1);if(e.key==='Escape')show(trail)});
const info=$('#infoDialog');$('#infoBtn').onclick=()=>info.showModal();$('#infoClose').onclick=()=>info.close();info.addEventListener('cancel',e=>{e.preventDefault();info.close()});buildTiles();
